spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

token:
  expiration_time: 86400000
  secret: '{cipher}5e4c240a6af39c94b5bbd62db4ad2974d171410b3cc259ec565646cb26a6958e' #user_token 암호화 - POST localhost:8888/encrypt
